"""Seed data for PurePeptide store - based on live purepeptide.bg structure."""

CDN = "https://purepeptide.bg/cdn/shop"

COLLECTIONS = [
    {
        "handle": "all-peptides",
        "title": "Всички пептиди",
        "title_en": "All Peptides",
        "description": "Пълен каталог на лиофилизирани пептиди с лабораторно доказана чистота над 99%.",
        "image": f"{CDN}/files/IMG_2354.webp",
        "sort_order": 0,
    },
    {
        "handle": "weight-loss",
        "title": "Отслабване",
        "title_en": "Weight Loss",
        "description": "Пептиди за метаболитна подкрепа и контрол на телесното тегло.",
        "image": f"{CDN}/collections/metabolizm-2324758_832fa7a8-ca99-4aa9-a2da-5338d75dd7d5.jpg",
        "sort_order": 1,
    },
    {
        "handle": "regeneration",
        "title": "Възстановяване",
        "title_en": "Recovery",
        "description": "Пептиди за тъканно възстановяване и регенерация.",
        "image": f"{CDN}/collections/vzstanovyavane-9259621.jpg",
        "sort_order": 2,
    },
    {
        "handle": "muscles",
        "title": "Мускули",
        "title_en": "Muscles",
        "description": "Подкрепа за мускулен растеж и спортно представяне.",
        "image": f"{CDN}/collections/muskuli-2808574.jpg",
        "sort_order": 3,
    },
    {
        "handle": "skin-longevity",
        "title": "Кожа",
        "title_en": "Skin & Longevity",
        "description": "Пептиди за здрава кожа и продължителна младост.",
        "image": f"{CDN}/collections/kozha-1728219.png",
        "sort_order": 4,
    },
    {
        "handle": "melanin-and-libido",
        "title": "Меланин",
        "title_en": "Melanin & Libido",
        "description": "Пептиди за пигментация и сексуално здраве.",
        "image": f"{CDN}/collections/melanin-2420930_d4d2a236-c6b8-40cf-9471-e5176caa3ea7.jpg",
        "sort_order": 5,
    },
    {
        "handle": "immune-system",
        "title": "Имунитет",
        "title_en": "Immunity",
        "description": "Пептиди за подкрепа на имунната система.",
        "image": f"{CDN}/collections/imunitet-3783452.jpg",
        "sort_order": 6,
    },
]

# Each product: handle, title, price (EUR cents), variants, image, collections, tags
PRODUCTS = [
    {
        "handle": "bpc-157",
        "title": "BPC-157 5mg/10mg",
        "subtitle": "Регенеративен пептид",
        "description": "BPC-157 (Body Protection Compound) е синтетичен пептид с 15 аминокиселини, изследван за тъканно възстановяване, защита на стомашно-чревния тракт и регенерация на сухожилия. Лиофилизиран, чистота >99% (HPLC + LC-MS, Janoshik Labs).",
        "image": f"{CDN}/files/bpc-157br5mg10mg-5909782_b2b5623f-2c10-4be8-a82f-502ea1c3cefb.png",
        "images": [
            f"{CDN}/files/bpc-157br5mg10mg-5909782_b2b5623f-2c10-4be8-a82f-502ea1c3cefb.png",
            f"{CDN}/files/bpc-157br5mg10mg-1385419_4f4138b6-1afa-45fd-81fc-2c565f6d5abc.png",
        ],
        "variants": [
            {"name": "5mg", "price_eur": 29.00, "stock": 50, "sku": "BPC-5"},
            {"name": "10mg", "price_eur": 49.00, "stock": 30, "sku": "BPC-10"},
        ],
        "collections": ["regeneration", "muscles"],
        "tags": ["bpc", "regeneration"],
    },
    {
        "handle": "cjc-1295",
        "title": "CJC-1295 (no DAC) 5mg",
        "subtitle": "GHRH аналог",
        "description": "CJC-1295 без DAC е модифициран фрагмент на GHRH, изследван за стимулиране на естествено производство на растежен хормон. Лиофилизиран, чистота >99%.",
        "image": f"{CDN}/files/cjc-1295-no-dacbr5mg-2052321_1247463f-acf2-41a5-80a6-f6dff48584af.png",
        "variants": [{"name": "5mg", "price_eur": 45.00, "stock": 40, "sku": "CJC-5"}],
        "collections": ["muscles", "regeneration"],
        "tags": ["ghrh", "muscle"],
    },
    {
        "handle": "dsip",
        "title": "DSIP (Delta Sleep Inducing Peptide) 5mg",
        "subtitle": "Сън и възстановяване",
        "description": "Делта сън-индуциращ пептид, изследван за подобряване на качеството на съня и невроендокринна модулация.",
        "image": f"{CDN}/files/dsip-delta-sleep-inducing-peptidebr5mg-7647068_f66d56ef-1657-4520-9b5c-94c3c08e887f.png",
        "variants": [{"name": "5mg", "price_eur": 39.00, "stock": 25, "sku": "DSIP-5"}],
        "collections": ["regeneration"],
        "tags": ["sleep"],
    },
    {
        "handle": "ghk-cu",
        "title": "GHK-Cu (skin glow) 100mg",
        "subtitle": "Меден трипептид",
        "description": "GHK-Cu е меден трипептид с активна роля в регенерацията на кожата, синтеза на колаген и защита срещу оксидативен стрес.",
        "image": f"{CDN}/files/ghk-cu-skin-glowbr100mg-4384070_9a5d0ca6-b42a-4dfe-bdd8-f9602f9660d9.png",
        "variants": [{"name": "100mg", "price_eur": 39.00, "stock": 0, "sku": "GHK-100"}],
        "collections": ["skin-longevity"],
        "tags": ["skin", "copper"],
    },
    {
        "handle": "ghrp-2",
        "title": "GHRP-2 5mg/10mg",
        "subtitle": "Стимулатор на растежен хормон",
        "description": "Растежен хормон-освобождаващ пептид с висока активност. Изследван за стимулиране на освобождаването на GH.",
        "image": f"{CDN}/files/ghrp-2br5mg10mg-6602292_96dff64b-ed3e-4106-8be5-9836d5d1e58f.png",
        "variants": [
            {"name": "5mg", "price_eur": 29.00, "stock": 35, "sku": "GHRP2-5"},
            {"name": "10mg", "price_eur": 49.00, "stock": 20, "sku": "GHRP2-10"},
        ],
        "collections": ["muscles"],
        "tags": ["ghrp"],
    },
    {
        "handle": "ghrp-6",
        "title": "GHRP-6 5mg",
        "subtitle": "Растежен хормон-освобождаващ пептид",
        "description": "GHRP-6 е хексапептид, изследван за стимулиране на освобождаването на растежен хормон.",
        "image": f"{CDN}/files/ghrp-6br5mg-6213283_249ea8e0-0b30-4eb6-b2f1-2e693cb95c5c.png",
        "variants": [{"name": "5mg", "price_eur": 29.00, "stock": 30, "sku": "GHRP6-5"}],
        "collections": ["muscles"],
        "tags": ["ghrp"],
    },
    {
        "handle": "hgh-frag-176-191",
        "title": "hGH frag (176-191) 5mg",
        "subtitle": "Фрагмент на GH",
        "description": "Фрагмент 176-191 на човешкия растежен хормон, изследван за метаболизма на мазнини.",
        "image": f"{CDN}/files/hgh-frag-176-191br5mg-3748012_c7410536-5990-4c10-9435-3a63dfd65ce5.png",
        "variants": [{"name": "5mg", "price_eur": 35.00, "stock": 28, "sku": "HGH-5"}],
        "collections": ["weight-loss"],
        "tags": ["fat-loss"],
    },
    {
        "handle": "igf-1-lr3",
        "title": "IGF-1 LR3 (Long arginine 3) 1mg",
        "subtitle": "Инсулиноподобен растежен фактор",
        "description": "IGF-1 LR3 е дългодействащ аналог на IGF-1, изследван за анаболни ефекти и регенерация.",
        "image": f"{CDN}/files/1-2_2f7ea207-3d0e-4104-8739-63a173bc50bc.png",
        "variants": [{"name": "1mg", "price_eur": 69.00, "stock": 15, "sku": "IGF-1"}],
        "collections": ["muscles"],
        "tags": ["igf"],
    },
    {
        "handle": "mots-c",
        "title": "MOTS-c 10mg",
        "subtitle": "Митохондриален пептид",
        "description": "MOTS-c е митохондриален пептид с 16 аминокиселини, изследван за метаболитна регулация.",
        "image": f"{CDN}/files/MOTS-c_4aea18a0-0bd0-4fb9-b3d4-a92d85a6d26b.png",
        "variants": [{"name": "10mg", "price_eur": 45.00, "stock": 22, "sku": "MOTS-10"}],
        "collections": ["regeneration", "weight-loss"],
        "tags": ["mitochondrial"],
    },
    {
        "handle": "pt-141",
        "title": "PT-141 10mg",
        "subtitle": "Bremelanotide",
        "description": "PT-141 (Bremelanotide) е меланокортинов агонист, изследван за сексуално здраве.",
        "image": f"{CDN}/files/pt-141-bremelanotidebr10mg-1779039_15608a5c-ae64-4a4b-ab7b-74fb471475a2.png",
        "variants": [{"name": "10mg", "price_eur": 49.00, "stock": 0, "sku": "PT-10"}],
        "collections": ["melanin-and-libido"],
        "tags": ["libido"],
    },
    {
        "handle": "tb-500",
        "title": "TB-500 (frag. 17-23) 10mg",
        "subtitle": "Тимозин фрагмент",
        "description": "Активният фрагмент на тимозин β-4, изследван за тъканно възстановяване и регенерация.",
        "image": f"{CDN}/files/tb-500-frag-17-23br5mg10mg-2753046_00c9e91e-c9ae-4c84-8262-6832dc337d9e.png",
        "variants": [{"name": "10mg", "price_eur": 49.00, "stock": 18, "sku": "TB-10"}],
        "collections": ["regeneration"],
        "tags": ["recovery"],
    },
    {
        "handle": "ipamorelin",
        "title": "Ипаморелин (Ipamorelin) 10mg",
        "subtitle": "Селективен GH секретагог",
        "description": "Ипаморелин е селективен пептиден секретагог на растежен хормон с минимални странични ефекти в изследванията.",
        "image": f"{CDN}/files/ipamorelin-ipamorelinbr10mg-9325709_a80fd981-aa41-4801-b17c-16cd74bfd1d2.png",
        "variants": [{"name": "10mg", "price_eur": 49.00, "stock": 0, "sku": "IPA-10"}],
        "collections": ["muscles"],
        "tags": ["gh"],
    },
    {
        "handle": "melanotan-i",
        "title": "Меланотан I (Melanotan I) 10mg",
        "subtitle": "Меланокортинов аналог",
        "description": "Меланотан I е синтетичен аналог на α-MSH, изследван за стимулиране на меланогенеза.",
        "image": f"{CDN}/files/melanotan-melanotan-ibr10mg-5045985_126df4ad-dfbe-4a5d-bbfd-ebb109b1f6e7.png",
        "variants": [{"name": "10mg", "price_eur": 49.00, "stock": 20, "sku": "MT1-10"}],
        "collections": ["melanin-and-libido"],
        "tags": ["melanin"],
    },
    {
        "handle": "retatrutide",
        "title": "Ретатрутид (Retatrutide) 5mg/10mg/30mg",
        "subtitle": "Троен агонист GIP/GLP-1/глюкагон",
        "description": "Ретатрутид е троен агонист на GIP, GLP-1 и глюкагонови рецептори, изследван за управление на затлъстяване.",
        "image": f"{CDN}/files/retatrutide5mg_4fd35b8c-6ce7-4612-8ba4-d78f598b07e2.png",
        "images": [
            f"{CDN}/files/retatrutide5mg_4fd35b8c-6ce7-4612-8ba4-d78f598b07e2.png",
            f"{CDN}/files/Retatrutide_10mg_8cf00e80-0c60-49f2-9024-4f960ea1466a.png",
            f"{CDN}/files/Retatrutide_30mg_f2b2f87c-a39c-402c-9d20-c3781bb3ad98.png",
        ],
        "variants": [
            {"name": "5mg", "price_eur": 59.00, "stock": 40, "sku": "RETA-5"},
            {"name": "10mg", "price_eur": 99.00, "stock": 25, "sku": "RETA-10"},
            {"name": "30mg", "price_eur": 249.00, "stock": 10, "sku": "RETA-30"},
        ],
        "collections": ["weight-loss"],
        "tags": ["glp1", "weight"],
        "featured": True,
    },
    {
        "handle": "semaglutide",
        "title": "Семаглутид (Semaglutide) 5mg/10mg",
        "subtitle": "GLP-1 агонист",
        "description": "Семаглутид е GLP-1 рецепторен агонист, изследван за гликемичен контрол и редукция на тегло.",
        "image": f"{CDN}/files/Semaglutide_5mg_55bfa366-6dfc-42f3-b518-7a25e8ceb136.png",
        "images": [
            f"{CDN}/files/Semaglutide_5mg_55bfa366-6dfc-42f3-b518-7a25e8ceb136.png",
            f"{CDN}/files/Semaglutide_10mg_7a642dc1-ec4f-41bc-b189-1ad6e84ac28d.png",
        ],
        "variants": [
            {"name": "5mg", "price_eur": 49.00, "stock": 30, "sku": "SEMA-5"},
            {"name": "10mg", "price_eur": 89.00, "stock": 18, "sku": "SEMA-10"},
        ],
        "collections": ["weight-loss"],
        "tags": ["glp1"],
        "featured": True,
    },
    {
        "handle": "sermorelin",
        "title": "Серморелин (Sermorelin) 5mg",
        "subtitle": "GHRH аналог",
        "description": "Серморелин е аналог на GHRH (1-29), изследван за стимулиране на естествена секреция на GH.",
        "image": f"{CDN}/files/sermorelin-sermorelinbr5mg10mg-2113533_2eb21a45-0060-4364-af55-c9df858579de.png",
        "variants": [{"name": "5mg", "price_eur": 59.00, "stock": 16, "sku": "SER-5"}],
        "collections": ["regeneration"],
        "tags": ["ghrh"],
    },
    {
        "handle": "thymosin-alpha-1",
        "title": "Тимозин алфа-1 (Thymosin alpha-1) 5mg",
        "subtitle": "Имуномодулатор",
        "description": "Тимозин α-1 е пептиден имуномодулатор, изследван за подкрепа на имунния отговор.",
        "image": f"{CDN}/files/timozin-alfa-1-thymosin-alpha-1br5mg-2531193_6bc18ff6-b9a4-4030-bb04-9c8e4cbfe924.png",
        "variants": [{"name": "5mg", "price_eur": 59.00, "stock": 12, "sku": "TA1-5"}],
        "collections": ["immune-system"],
        "tags": ["immune"],
    },
    {
        "handle": "thymosin-beta-4",
        "title": "Тимозин бета-4 (Thymosin beta-4) 5mg",
        "subtitle": "Регенеративен пептид",
        "description": "Тимозин β-4 е 43-аминокиселинен пептид, изследван за тъканна регенерация и имунна функция.",
        "image": f"{CDN}/files/timozin-beta-4brthymosin-beta-4-5mg-9632338_2d3f8e1a-c921-4ca6-8088-83ed4ff29bce.png",
        "variants": [{"name": "5mg", "price_eur": 49.00, "stock": 22, "sku": "TB4-5"}],
        "collections": ["regeneration", "immune-system"],
        "tags": ["recovery"],
    },
    {
        "handle": "tirzepatide",
        "title": "Тирзепатид (Tirzepatide) 5mg/10mg",
        "subtitle": "Двоен GIP/GLP-1 агонист",
        "description": "Тирзепатид е двоен GIP/GLP-1 рецепторен агонист, изследван за гликемичен контрол и тегло.",
        "image": f"{CDN}/files/Tirzepatide5mg_ff19f292-884d-4c41-be46-84615a825b0a.png",
        "images": [
            f"{CDN}/files/Tirzepatide5mg_ff19f292-884d-4c41-be46-84615a825b0a.png",
            f"{CDN}/files/Tirzepatide10mg_23154762-1a47-4286-91e3-e067e3a7c9ea.png",
        ],
        "variants": [
            {"name": "5mg", "price_eur": 59.00, "stock": 28, "sku": "TIRZ-5"},
            {"name": "10mg", "price_eur": 99.00, "stock": 15, "sku": "TIRZ-10"},
        ],
        "collections": ["weight-loss"],
        "tags": ["glp1"],
        "featured": True,
    },
    {
        "handle": "hexarelin",
        "title": "Хексарелин (Hexarelin) 2mg/5mg",
        "subtitle": "GH секретагог",
        "description": "Хексарелин е синтетичен растежен хормон-освобождаващ пептид с висока активност.",
        "image": f"{CDN}/files/kheksarelin-hexarelinbr2mg5mg-1535587_5da77e4e-6acd-40f3-bfb8-ca3220bfb7db.png",
        "variants": [
            {"name": "2mg", "price_eur": 35.00, "stock": 20, "sku": "HEX-2"},
            {"name": "5mg", "price_eur": 59.00, "stock": 12, "sku": "HEX-5"},
        ],
        "collections": ["muscles"],
        "tags": ["ghrp"],
    },
]

ARTICLES = [
    {
        "handle": "retatrutide-study",
        "title": "Ретатрутид – троен агонист на GIP, GLP-1 и глюкагонови рецептори при затлъстяване",
        "excerpt": "Преглед на клиничните данни за ретатрутид и потенциала му за управление на наднормено тегло.",
        "image": f"{CDN}/articles/RETA_212b522f-37fe-43ea-9b86-55c24aaa3cda.png",
    },
    {
        "handle": "ghk-cu-regeneration",
        "title": "Регенеративни и защитни действия на GHK-Cu в светлината на новите генни данни",
        "excerpt": "Как медният трипептид GHK-Cu повлиява генната експресия и регенерацията.",
        "image": f"{CDN}/articles/GHK_7187505f-9778-4b92-a1a9-052075102002.png",
    },
    {
        "handle": "cjc-1295-gh-axis",
        "title": "Активиране на оста GH/IGF-1 чрез CJC-1295 – дългодействащ аналог на GHRH",
        "excerpt": "Механизъм на действие на CJC-1295 и дългосрочни ефекти върху растежния хормон.",
        "image": f"{CDN}/articles/CJC_0246450d-b7b6-413c-b992-0bf356da7ab1.png",
    },
    {
        "handle": "bpc-157-pharmacokinetics",
        "title": "BPC-157: Фармакокинетика, безопасност и потенциал за тъканна регенерация",
        "excerpt": "Преглед на изследванията за BPC-157 и неговия регенеративен потенциал.",
        "image": f"{CDN}/articles/BPC_8baa7944-4792-48ee-82aa-2a3b29ba9368.png",
    },
]

DEFAULT_SETTINGS = {
    "site_name": "PurePeptide",
    "tagline": "Лиофилизирани пептиди с лабораторно доказана чистота над 99%",
    "hero_title": "PurePeptide",
    "hero_subtitle": "Лиофилизираните пептиди са златен стандарт за качество и са стабилни до 2 години, за разлика от готовите разтвори със срок около месец. Пептидите ни са тествани от Janoshik Labs.",
    "hero_cta_primary": "Пазарувай Пептиди",
    "hero_cta_secondary": "Виж Сертификати",
    "announcement": "Експресна доставка с Еконт • Наложен платеж • Janoshik Labs тествани",
    "currency_primary": "EUR",
    "currency_secondary": "BGN",
    "fx_rate": 1.95583,  # 1 EUR = 1.95583 BGN (peg)
    "footer_text": "© 2026 PurePeptide. Информацията на този уебсайт е с информативен характер. Продуктите са за научноизследователски цели.",
    "contact_email": "info@purepeptide.bg",
    "contact_phone": "+359 88 123 4567",
}
