"""Translate the long-form storefront blocks (product page blocks, trust cards, FAQ) from Bulgarian
into the 9 remaining locales with Claude and write frontend/src/i18n/blocksGenerated.js.

Run: python backend/tools/translate_static_blocks.py
"""
import asyncio
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[1] / ".env")
from i18n import ai_translate_chunked  # noqa: E402

TARGETS = ["en", "fr", "de", "cz", "hu", "pl", "sk", "si", "gr", "ro"]

PRODUCT_BLOCKS = [
    ("✅ Анализ на качество - Janoshik",
     "<p>Нашите пептиди се произвеждат при спазване на строги стандарти за <strong>качество и контрол</strong>. Всеки продукт се доставя в <strong>лиофилизирана форма</strong>, което осигурява <strong>стабилност</strong> и предотвратява влошаване на качеството по време на транспорт. Тестваме всяка партида.</p>"),
    ("❌ Защо не предлагаме разтвори",
     "<p>Не предлагаме готови водни разтвори, защото в тях пептидните молекули са значително <strong>по-нестабилни</strong>. Присъствието на вода ускорява хидролиза, окисление и агрегация. Лиофилизираната форма съхранява структурата до <strong>24 месеца</strong> при хладилни условия.</p>"),
    ("❄️ Правилно съхранение",
     "<p>При съхранение в хладилник при <strong>2°C – 8°C</strong> срокът на годност е до 24 месеца. На стайна температура стабилността се задържа около 3–4 месеца. След реконституиране съхранявайте в хладилник до 4 седмици.</p>"),
    ("📦 Доставка",
     "<p>Осигуряваме бърза и сигурна доставка с проследяване чрез местен куриер. Поръчките се обработват в рамките на 1–3 работни дни и се доставят до офис, автоматичен пакетомат или личен адрес. След изпращане получавате имейл с потвърждение.</p>"),
    ("📖 Разтваряне",
     "<ol><li>Работете в чиста среда и използвайте стерилни консумативи.</li><li>Изтеглете необходимия обем бактериостатична вода със стерилна спринцовка.</li><li>Насочете иглата към вътрешната стена на флакона и бавно добавете водата.</li><li>Завъртете леко флакона, докато прахът се разтвори напълно.</li><li>Съхранявайте реконституирания разтвор при 2–8°C до 4-6 седмици.</li></ol>"),
]

TRUST_CARDS = [
    ("Прозрачност във всяка партида",
     "PurePeptide поставя акцент върху ясна продуктова информация, лабораторни анализи и проследимост на партидите. Така всяко решение може да бъде базирано на данни, а не на преувеличени твърдения."),
    ("Информация с научен фокус",
     "Описанията ни следват неутрален и изследователски подход, основан на публикувана научна литература и лабораторен контекст. Целта е съдържанието да бъде точно, разбираемо и полезно."),
    ("Качество и контрол",
     "Всяка партида преминава HPLC и LC-MS анализ от независимата лаборатория Janoshik. Сертификатите са достъпни директно в продуктовите страници."),
]

FAQ_ITEMS = [
    ("Какво отличава пептидите на PurePeptide?",
     "Прозрачност и контрол на качеството. Всеки продукт е лиофилизиран за по-дълъг срок на съхранение и е преминал HPLC и LC-MS анализ с чистота над 99%. Тестовете се извършват от чешката лаборатория Janoshik."),
    ("Как мога да проверя сертификатите за анализ?",
     "Всеки продукт разполага със сертификат за анализ (CoA), извършен от Janoshik Labs. Документите са достъпни в продуктовите страници и съдържат партиден номер."),
    ("Колко време са стабилни неразтворените пептиди?",
     "В лиофилизиран вид при 2–8°C пептидите запазват стабилност до 24 месеца. При стайна температура – около 3–4 месеца."),
    ("Колко време отнема доставката?",
     "Пратките се изпращат с проследяване чрез местен куриер и обикновено пристигат в рамките на 1–3 работни дни."),
]

EMOJI = ["✅", "❌", "❄️", "📦", "📖"]


def source_fields():
    src = {}
    for i, (title, html) in enumerate(PRODUCT_BLOCKS):
        src[f"pb{i}_title"] = title.split(" ", 1)[1] if title[0] in "✅❌📦📖" or title.startswith("❄") else title
        src[f"pb{i}_html"] = html
    for i, (title, body) in enumerate(TRUST_CARDS):
        src[f"tc{i}_title"] = title
        src[f"tc{i}_body"] = body
    for i, (q, a) in enumerate(FAQ_ITEMS):
        src[f"fq{i}_q"] = q
        src[f"fq{i}_a"] = a
    return src


def js_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render(data):
    lines = ["/* AUTO-GENERATED by backend/tools/translate_static_blocks.py — do not edit by hand.",
             "   Long-form storefront copy (product page blocks, trust cards, FAQ) in every locale. */",
             ""]
    for name, kind in (("PRODUCT_BLOCKS_GEN", "pb"), ("TRUST_CARDS_GEN", "tc"), ("FAQ_GEN", "fq")):
        lines.append(f"export const {name} = {{")
        for loc in TARGETS:
            vals = data.get(loc)
            if not vals:
                continue
            lines.append(f"  {loc}: [")
            if kind == "pb":
                for i in range(len(PRODUCT_BLOCKS)):
                    title = f"{EMOJI[i]} {vals[f'pb{i}_title']}"
                    lines.append(f"    {{ title: {js_string(title)}, html: {js_string(vals[f'pb{i}_html'])} }},")
            elif kind == "tc":
                for i in range(len(TRUST_CARDS)):
                    lines.append(f"    {{ n: \"0{i + 1}\", title: {js_string(vals[f'tc{i}_title'])}, "
                                 f"body: {js_string(vals[f'tc{i}_body'])} }},")
            else:
                for i in range(len(FAQ_ITEMS)):
                    lines.append(f"    {{ q: {js_string(vals[f'fq{i}_q'])}, a: {js_string(vals[f'fq{i}_a'])} }},")
            lines.append("  ],")
        lines.append("};")
        lines.append("")
    return "\n".join(lines)


async def main():
    src = source_fields()
    print(f"translating {len(src)} fields into {len(TARGETS)} locales…")
    data = await ai_translate_chunked(src, TARGETS, context=(
        "Long-form copy shown on a peptide research storefront. Keep HTML tags intact, keep the "
        "research-oriented tone, do not mention any specific courier brand."), chunk=1)
    missing = [l for l in TARGETS if l not in data or len(data[l]) < len(src)]
    if missing:
        print("INCOMPLETE:", missing, file=sys.stderr)
    out = Path(__file__).resolve().parents[2] / "frontend/src/i18n/blocksGenerated.js"
    out.write_text(render(data), encoding="utf-8")
    print("wrote", out, "locales:", sorted(data))


if __name__ == "__main__":
    asyncio.run(main())
