/* AUTO-GENERATED by backend/tools/translate_static_blocks.py — do not edit by hand.
   Long-form storefront copy (product page blocks, trust cards, FAQ) in every locale. */

export const PRODUCT_BLOCKS_GEN = {
  en: [
    { title: "✅ Quality Analysis - Janoshik", html: "<p>Our peptides are manufactured in compliance with strict <strong>quality and control</strong> standards. Every product is delivered in <strong>lyophilized form</strong>, which ensures <strong>stability</strong> and prevents quality degradation during transport. We test every batch.</p>" },
    { title: "❌ Why We Don't Offer Solutions", html: "<p>We do not offer ready-made aqueous solutions, because in them peptide molecules are significantly <strong>less stable</strong>. The presence of water accelerates hydrolysis, oxidation, and aggregation. The lyophilized form preserves the structure for up to <strong>24 months</strong> under refrigerated conditions.</p>" },
    { title: "❄️ Proper Storage", html: "<p>When stored in a refrigerator at <strong>2°C – 8°C</strong>, the shelf life is up to 24 months. At room temperature, stability is maintained for about 3–4 months. After reconstitution, store in a refrigerator for up to 4 weeks.</p>" },
    { title: "📦 Delivery", html: "<p>We provide fast and reliable delivery with tracking via a local courier. Orders are processed within 1–3 business days and delivered to an office, an automated parcel locker, or a personal address. After shipping, you receive a confirmation email.</p>" },
    { title: "📖 Reconstitution", html: "<ol><li>Work in a clean environment and use sterile supplies.</li><li>Draw the required volume of bacteriostatic water with a sterile syringe.</li><li>Direct the needle toward the inner wall of the vial and slowly add the water.</li><li>Gently swirl the vial until the powder dissolves completely.</li><li>Store the reconstituted solution at 2–8°C for up to 4-6 weeks.</li></ol>" },
  ],
  fr: [
    { title: "✅ Analyse de qualité - Janoshik", html: "<p>Nos peptides sont produits dans le respect de normes strictes de <strong>qualité et de contrôle</strong>. Chaque produit est livré sous <strong>forme lyophilisée</strong>, ce qui assure une <strong>stabilité</strong> et prévient la dégradation de la qualité pendant le transport. Nous testons chaque lot.</p>" },
    { title: "❌ Pourquoi nous ne proposons pas de solutions", html: "<p>Nous ne proposons pas de solutions aqueuses prêtes à l'emploi, car les molécules peptidiques y sont nettement <strong>moins stables</strong>. La présence d'eau accélère l'hydrolyse, l'oxydation et l'agrégation. La forme lyophilisée préserve la structure jusqu'à <strong>24 mois</strong> dans des conditions réfrigérées.</p>" },
    { title: "❄️ Conservation correcte", html: "<p>Conservés au réfrigérateur entre <strong>2°C et 8°C</strong>, la durée de conservation atteint 24 mois. À température ambiante, la stabilité est maintenue environ 3 à 4 mois. Après reconstitution, conserver au réfrigérateur jusqu'à 4 semaines.</p>" },
    { title: "📦 Livraison", html: "<p>Nous assurons une livraison rapide et sécurisée avec suivi via un transporteur local. Les commandes sont traitées dans un délai de 1 à 3 jours ouvrables et livrées à un point relais, un casier automatique ou une adresse personnelle. Après l'expédition, vous recevez un e-mail de confirmation.</p>" },
    { title: "📖 Reconstitution", html: "<ol><li>Travaillez dans un environnement propre et utilisez des consommables stériles.</li><li>Prélevez le volume nécessaire d'eau bactériostatique avec une seringue stérile.</li><li>Dirigez l'aiguille vers la paroi interne du flacon et ajoutez lentement l'eau.</li><li>Faites tourner légèrement le flacon jusqu'à dissolution complète de la poudre.</li><li>Conservez la solution reconstituée à 2–8°C pendant 4 à 6 semaines maximum.</li></ol>" },
  ],
  de: [
    { title: "✅ Qualitätsanalyse - Janoshik", html: "<p>Unsere Peptide werden unter Einhaltung strenger <strong>Qualitäts- und Kontrollstandards</strong> hergestellt. Jedes Produkt wird in <strong>lyophilisierter Form</strong> geliefert, was <strong>Stabilität</strong> gewährleistet und eine Qualitätsminderung während des Transports verhindert. Wir testen jede Charge.</p>" },
    { title: "❌ Warum wir keine Lösungen anbieten", html: "<p>Wir bieten keine fertigen wässrigen Lösungen an, da die Peptidmoleküle darin deutlich <strong>instabiler</strong> sind. Die Anwesenheit von Wasser beschleunigt Hydrolyse, Oxidation und Aggregation. Die lyophilisierte Form bewahrt die Struktur bis zu <strong>24 Monate</strong> unter Kühlbedingungen.</p>" },
    { title: "❄️ Richtige Lagerung", html: "<p>Bei Lagerung im Kühlschrank bei <strong>2°C – 8°C</strong> beträgt die Haltbarkeit bis zu 24 Monate. Bei Raumtemperatur bleibt die Stabilität etwa 3–4 Monate erhalten. Nach der Rekonstitution im Kühlschrank bis zu 4 Wochen lagern.</p>" },
    { title: "📦 Lieferung", html: "<p>Wir bieten eine schnelle und sichere Lieferung mit Sendungsverfolgung durch einen lokalen Kurierdienst. Bestellungen werden innerhalb von 1–3 Werktagen bearbeitet und an ein Büro, einen Paketautomaten oder eine private Adresse geliefert. Nach dem Versand erhalten Sie eine Bestätigungs-E-Mail.</p>" },
    { title: "📖 Auflösung", html: "<ol><li>Arbeiten Sie in einer sauberen Umgebung und verwenden Sie steriles Zubehör.</li><li>Ziehen Sie mit einer sterilen Spritze das benötigte Volumen an bakteriostatischem Wasser auf.</li><li>Richten Sie die Nadel auf die Innenwand des Fläschchens und geben Sie das Wasser langsam hinzu.</li><li>Drehen Sie das Fläschchen leicht, bis sich das Pulver vollständig aufgelöst hat.</li><li>Lagern Sie die rekonstituierte Lösung bei 2–8°C bis zu 4-6 Wochen.</li></ol>" },
  ],
  cz: [
    { title: "✅ Analýza kvality – Janoshik", html: "<p>Naše peptidy se vyrábějí při dodržování strogých standardů <strong>kvality a kontroly</strong>. Každý produkt je dodáván v <strong>lyofilizované formě</strong>, což zajišťuje <strong>stabilitu</strong> a zabraňuje zhoršení kvality během přepravy. Testujeme každou šarži.</p>" },
    { title: "❌ Proč nenabízíme roztoky", html: "<p>Nenabízíme hotové vodné roztoky, protože v nich jsou peptidové molekuly výrazně <strong>méně stabilní</strong>. Přítomnost vody urychluje hydrolýzu, oxidaci a agregaci. Lyofilizovaná forma zachovává strukturu až <strong>24 měsíců</strong> při chladírenských podmínkách.</p>" },
    { title: "❄️ Správné uchovávání", html: "<p>Při uchovávání v chladničce při teplotě <strong>2 °C – 8 °C</strong> je doba použitelnosti až 24 měsíců. Při pokojové teplotě se stabilita udržuje přibližně 3–4 měsíce. Po rekonstituci uchovávejte v chladničce po dobu až 4 týdnů.</p>" },
    { title: "📦 Doprava", html: "<p>Zajišťujeme rychlé a bezpečné doručení se sledováním prostřednictvím místního přepravce. Objednávky jsou zpracovány do 1–3 pracovních dnů a doručeny na pobočku, do výdejního boxu nebo na osobní adresu. Po odeslání obdržíte e-mail s potvrzením.</p>" },
    { title: "📖 Rozpouštění", html: "<ol><li>Pracujte v čistém prostředí a používejte sterilní pomůcky.</li><li>Nasajte potřebný objem bakteriostatické vody sterilní stříkačkou.</li><li>Namiřte jehlu na vnitřní stěnu lahvičky a pomalu přidejte vodu.</li><li>Lahvičku lehce otáčejte, dokud se prášek úplně nerozpustí.</li><li>Rekonstituovaný roztok uchovávejte při 2–8 °C po dobu až 4–6 týdnů.</li></ol>" },
  ],
  hu: [
    { title: "✅ Minőségvizsgálat - Janoshik", html: "<p>Pepdideinket szigorú <strong>minőségi és ellenőrzési</strong> szabványok betartásával gyártjuk. Minden termék <strong>liofilizált formában</strong> kerül kiszállításra, ami biztosítja a <strong>stabilitást</strong>, és megakadályozza a minőségromlást szállítás közben. Minden gyártási tételt bevizsgálunk.</p>" },
    { title: "❌ Miért nem kínálunk oldatokat", html: "<p>Nem kínálunk kész vizes oldatokat, mert azokban a peptidmolekulák jelentősen <strong>instabilabbak</strong>. A víz jelenléte felgyorsítja a hidrolízist, oxidációt és aggregációt. A liofilizált forma <strong>24 hónapig</strong> megőrzi a szerkezetet hűtött körülmények között.</p>" },
    { title: "❄️ Helyes tárolás", html: "<p>Hűtőszekrényben, <strong>2°C – 8°C</strong> hőmérsékleten tárolva a szavatossági idő akár 24 hónap is lehet. Szobahőmérsékleten a stabilitás körülbelül 3–4 hónapig marad fenn. Rekonstituálás után hűtőszekrényben tárolja legfeljebb 4 hétig.</p>" },
    { title: "📦 Szállítás", html: "<p>Gyors és biztonságos szállítást biztosítunk nyomon követéssel helyi futárszolgálat segítségével. A rendeléseket 1–3 munkanapon belül feldolgozzuk, és irodába, csomagautomatába vagy személyes címre szállítjuk. A feladás után visszaigazoló e-mailt kap.</p>" },
    { title: "📖 Feloldás", html: "<ol><li>Dolgozzon tiszta környezetben, és használjon steril kellékeket.</li><li>Szívja fel a szükséges mennyiségű baktériosztatikus vizet steril fecskendővel.</li><li>Irányítsa a tűt az injekciós üveg belső falára, és lassan adja hozzá a vizet.</li><li>Óvatosan forgassa az üveget, amíg a por teljesen fel nem oldódik.</li><li>Az rekonstituált oldatot 2–8°C-on tárolja, legfeljebb 4-6 hétig.</li></ol>" },
  ],
  pl: [
    { title: "✅ Analiza jakości - Janoshik", html: "<p>Nasze peptydy są produkowane z zachowaniem ścisłych standardów <strong>jakości i kontroli</strong>. Każdy produkt jest dostarczany w <strong>formie liofilizowanej</strong>, co zapewnia <strong>stabilność</strong> i zapobiega utracie jakości podczas transportu. Testujemy każdą partię.</p>" },
    { title: "❌ Dlaczego nie oferujemy roztworów", html: "<p>Nie oferujemy gotowych roztworów wodnych, ponieważ molekuły peptydów są w nich znacznie <strong>mniej stabilne</strong>. Obecność wody przyspiesza hydrolizę, oksydację i agregację. Forma liofilizowana zachowuje strukturę do <strong>24 miesięcy</strong> w warunkach chłodniczych.</p>" },
    { title: "❄️ Prawidłowe przechowywanie", html: "<p>Przy przechowywaniu w lodówce w temperaturze <strong>2°C – 8°C</strong> okres trwałości sięga 24 miesięcy. W temperaturze pokojowej stabilność utrzymuje się około 3–4 miesiące. Po rekonstytucji przechowuj w lodówce do 4 tygodni.</p>" },
    { title: "📦 Dostawa", html: "<p>Zapewniamy szybką i bezpieczną dostawę z możliwością śledzenia przesyłki przez lokalnego kuriera. Zamówienia są realizowane w ciągu 1–3 dni roboczych i dostarczane do biura, automatu paczkowego lub na adres domowy. Po wysyłce otrzymasz e-mail z potwierdzeniem.</p>" },
    { title: "📖 Rozpuszczanie", html: "<ol><li>Pracuj w czystym środowisku i używaj sterylnych materiałów.</li><li>Za pomocą sterylnej strzykawki pobierz wymaganą objętość wody bakteriostatycznej.</li><li>Skieruj igłę w stronę wewnętrznej ścianki fiolki i powoli dodaj wodę.</li><li>Delikatnie obróć fiolkę, aż proszek całkowicie się rozpuści.</li><li>Przechowuj zrekonstytuowany roztwór w temperaturze 2–8°C do 4-6 tygodni.</li></ol>" },
  ],
  sk: [
    { title: "✅ Analýza kvality - Janoshik", html: "<p>Naše peptidy sa vyrábajú v súlade s prísnymi štandardmi <strong>kvality a kontroly</strong>. Každý produkt je dodávaný v <strong>lyofilizovanej forme</strong>, čo zabezpečuje <strong>stabilitu</strong> a zabraňuje zhoršeniu kvality počas prepravy. Testujeme každú šaržu.</p>" },
    { title: "❌ Prečo nenúkame roztoky", html: "<p>Nenúkame hotové vodné roztoky, pretože v nich sú peptidové molekuly výrazne <strong>menej stabilné</strong>. Prítomnosť vody urýchľuje hydrolýzu, oxidáciu a agregáciu. Lyofilizovaná forma zachováva štruktúru až <strong>24 mesiacov</strong> pri chladení.</p>" },
    { title: "❄️ Správne uchovávanie", html: "<p>Pri uchovávaní v chladničke pri <strong>2°C – 8°C</strong> je doba použiteľnosti až 24 mesiacov. Pri izbovej teplote sa stabilita udrží približne 3–4 mesiace. Po rekonštitúcii uchovávajte v chladničke maximálne 4 týždne.</p>" },
    { title: "📦 Doručenie", html: "<p>Zabezpečujeme rýchle a bezpečné doručenie so sledovaním prostredníctvom miestneho kuriéra. Objednávky sa spracúvajú do 1–3 pracovných dní a doručujú sa do kancelárie, výdajného automatu alebo na osobnú adresu. Po odoslaní dostanete e-mail s potvrdením.</p>" },
    { title: "📖 Rozpustenie", html: "<ol><li>Pracujte v čistom prostredí a používajte sterilné pomôcky.</li><li>Sterilnou striekačkou odoberte potrebný objem bakteriostatickej vody.</li><li>Nasmerujte ihlu k vnútornej stene liekovky a pomaly pridajte vodu.</li><li>Liekovkou mierne krúžte, kým sa prášok úplne nerozpustí.</li><li>Rekonštituovaný roztok uchovávajte pri 2–8°C až 4-6 týždňov.</li></ol>" },
  ],
  si: [
    { title: "✅ Analiza kakovosti - Janoshik", html: "<p>Naši peptidi se proizvajajo ob upoštevanju strogih standardov <strong>kakovosti in nadzora</strong>. Vsak izdelek je dobavljen v <strong>liofilizirani obliki</strong>, kar zagotavlja <strong>stabilnost</strong> in preprečuje poslabšanje kakovosti med transportom. Testiramo vsako serijo.</p>" },
    { title: "❌ Zakaj ne ponujamo raztopin", html: "<p>Ne ponujamo pripravljenih vodnih raztopin, ker so v njih peptidne molekule znatno <strong>manj stabilne</strong>. Prisotnost vode pospešuje hidrolizo, oksidacijo in agregacijo. Liofilizirana oblika ohranja strukturo do <strong>24 mesecev</strong> v hladilnih pogojih.</p>" },
    { title: "❄️ Pravilno shranjevanje", html: "<p>Pri shranjevanju v hladilniku pri <strong>2°C – 8°C</strong> je rok uporabe do 24 mesecev. Pri sobni temperaturi se stabilnost ohranja približno 3–4 mesece. Po rekonstituciji shranjujte v hladilniku do 4 tedne.</p>" },
    { title: "📦 Dostava", html: "<p>Zagotavljamo hitro in zanesljivo dostavo s sledenjem prek lokalnega kurirja. Naročila se obdelajo v roku 1–3 delovnih dni in dostavijo v pisarno, avtomatski paketomat ali na osebni naslov. Po pošiljanju prejmete e-poštno potrdilo.</p>" },
    { title: "📖 Raztapljanje", html: "<ol><li>Delajte v čistem okolju in uporabljajte sterilne pripomočke.</li><li>S sterilno brizgo izmerite potrebno količino bakteriostatske vode.</li><li>Iglo usmerite proti notranji steni viale in počasi dodajte vodo.</li><li>Rahlo zavrtite vialo, dokler se prah popolnoma ne raztopi.</li><li>Rekonstituirano raztopino shranjujte pri 2–8°C do 4-6 tednov.</li></ol>" },
  ],
  gr: [
    { title: "✅ Ανάλυση Ποιότητας - Janoshik", html: "<p>Τα πεπτίδιά μας παράγονται τηρώντας αυστηρά πρότυπα <strong>ποιότητας και ελέγχου</strong>. Κάθε προϊόν παραδίδεται σε <strong>λυοφιλιωμένη μορφή</strong>, η οποία εξασφαλίζει <strong>σταθερότητα</strong> και αποτρέπει την υποβάθμιση της ποιότητας κατά τη μεταφορά. Δοκιμάζουμε κάθε παρτίδα.</p>" },
    { title: "❌ Γιατί δεν προσφέρουμε διαλύματα", html: "<p>Δεν προσφέρουμε έτοιμα υδατικά διαλύματα, διότι σε αυτά τα μόρια των πεπτιδίων είναι σημαντικά <strong>πιο ασταθή</strong>. Η παρουσία νερού επιταχύνει την υδρόλυση, την οξείδωση και τη συσσωμάτωση. Η λυοφιλιωμένη μορφή διατηρεί τη δομή έως <strong>24 μήνες</strong> υπό ψυκτικές συνθήκες.</p>" },
    { title: "❄️ Σωστή αποθήκευση", html: "<p>Κατά την αποθήκευση σε ψυγείο στους <strong>2°C – 8°C</strong> η διάρκεια ζωής φτάνει έως 24 μήνες. Σε θερμοκρασία δωματίου η σταθερότητα διατηρείται περίπου 3–4 μήνες. Μετά την ανασύσταση, αποθηκεύστε σε ψυγείο έως 4 εβδομάδες.</p>" },
    { title: "📦 Παράδοση", html: "<p>Εξασφαλίζουμε γρήγορη και ασφαλή παράδοση με ιχνηλάτηση μέσω τοπικής μεταφορικής εταιρείας. Οι παραγγελίες επεξεργάζονται εντός 1–3 εργάσιμων ημερών και παραδίδονται σε γραφείο, αυτόματο θυρίδα παραλαβής ή προσωπική διεύθυνση. Μετά την αποστολή λαμβάνετε email επιβεβαίωσης.</p>" },
    { title: "📖 Ανασύσταση", html: "<ol><li>Εργαστείτε σε καθαρό περιβάλλον και χρησιμοποιήστε στείρα αναλώσιμα.</li><li>Αναρροφήστε την απαιτούμενη ποσότητα βακτηριοστατικού νερού με στείρα σύριγγα.</li><li>Κατευθύνετε τη βελόνα προς το εσωτερικό τοίχωμα του φιαλιδίου και προσθέστε αργά το νερό.</li><li>Περιστρέψτε ελαφρά το φιαλίδιο μέχρι η σκόνη να διαλυθεί πλήρως.</li><li>Αποθηκεύστε το ανασυσταθέν διάλυμα στους 2–8°C για έως 4-6 εβδομάδες.</li></ol>" },
  ],
  ro: [
    { title: "✅ Analiza calității - Janoshik", html: "<p>Peptidele noastre sunt produse cu respectarea unor standarde stricte de <strong>calitate și control</strong>. Fiecare produs este livrat în <strong>formă liofilizată</strong>, ceea ce asigură <strong>stabilitate</strong> și previne deteriorarea calității în timpul transportului. Testăm fiecare lot.</p>" },
    { title: "❌ De ce nu oferim soluții", html: "<p>Nu oferim soluții apoase gata preparate, deoarece în acestea moleculele peptidice sunt semnificativ <strong>mai instabile</strong>. Prezența apei accelerează hidroliza, oxidarea și agregarea. Forma liofilizată păstrează structura până la <strong>24 de luni</strong> în condiții de refrigerare.</p>" },
    { title: "❄️ Depozitare corectă", html: "<p>La depozitare în frigider, la <strong>2°C – 8°C</strong>, termenul de valabilitate este de până la 24 de luni. La temperatura camerei, stabilitatea se menține aproximativ 3–4 luni. După reconstituire, păstrați în frigider până la 4 săptămâni.</p>" },
    { title: "📦 Livrare", html: "<p>Asigurăm livrare rapidă și sigură cu urmărire prin curier local. Comenzile sunt procesate în termen de 1–3 zile lucrătoare și sunt livrate la birou, la un automat de colete sau la adresa personală. După expediere, veți primi un e-mail de confirmare.</p>" },
    { title: "📖 Reconstituire", html: "<ol><li>Lucrați într-un mediu curat și folosiți consumabile sterile.</li><li>Trageți volumul necesar de apă bacteriostatică cu o seringă sterilă.</li><li>Îndreptați acul spre peretele interior al flaconului și adăugați încet apa.</li><li>Rotiți ușor flaconul până când praful se dizolvă complet.</li><li>Păstrați soluția reconstituită la 2–8°C timp de până la 4-6 săptămâni.</li></ol>" },
  ],
};

export const TRUST_CARDS_GEN = {
  en: [
    { n: "01", title: "Transparency in Every Batch", body: "PurePeptide places emphasis on clear product information, laboratory analyses, and batch traceability. This way, every decision can be based on data, not exaggerated claims." },
    { n: "02", title: "Information with a Scientific Focus", body: "Our descriptions follow a neutral and research-oriented approach, based on published scientific literature and laboratory context. The goal is for the content to be accurate, understandable, and useful." },
    { n: "03", title: "Quality and Control", body: "Every batch undergoes HPLC and LC-MS analysis by the independent laboratory Janoshik. Certificates are available directly on the product pages." },
  ],
  fr: [
    { n: "01", title: "Transparence pour chaque lot", body: "PurePeptide met l'accent sur une information produit claire, des analyses de laboratoire et la traçabilité des lots. Ainsi, chaque décision peut être basée sur des données plutôt que sur des affirmations exagérées." },
    { n: "02", title: "Information à orientation scientifique", body: "Nos descriptions suivent une approche neutre et axée sur la recherche, fondée sur la littérature scientifique publiée et le contexte de laboratoire. L'objectif est que le contenu soit précis, compréhensible et utile." },
    { n: "03", title: "Qualité et contrôle", body: "Chaque lot fait l'objet d'une analyse HPLC et LC-MS par le laboratoire indépendant Janoshik. Les certificats sont disponibles directement sur les pages produits." },
  ],
  de: [
    { n: "01", title: "Transparenz in jeder Charge", body: "PurePeptide legt Wert auf klare Produktinformationen, Laboranalysen und Chargen-Rückverfolgbarkeit. So kann jede Entscheidung auf Daten basieren und nicht auf übertriebenen Behauptungen." },
    { n: "02", title: "Informationen mit wissenschaftlichem Fokus", body: "Unsere Beschreibungen folgen einem neutralen und forschungsorientierten Ansatz, basierend auf veröffentlichter wissenschaftlicher Literatur und Laborkontext. Ziel ist es, dass der Inhalt präzise, verständlich und nützlich ist." },
    { n: "03", title: "Qualität und Kontrolle", body: "Jede Charge durchläuft eine HPLC- und LC-MS-Analyse durch das unabhängige Labor Janoshik. Die Zertifikate sind direkt auf den Produktseiten verfügbar." },
  ],
  cz: [
    { n: "01", title: "Transparentnost v každé šarži", body: "PurePeptide klade důraz na jasné produktové informace, laboratorní analýzy a sledovatelnost šarží. Díky tomu může být každé rozhodnutí založeno na datech, nikoli na přehnaných tvrzeních." },
    { n: "02", title: "Informace se zaměřením na vědu", body: "Naše popisy se řídí neutrálním a výzkumně orientovaným přístupem založeným na publikované vědecké literatuře a laboratorním kontextu. Cílem je, aby byl obsah přesný, srozumitelný a užitečný." },
    { n: "03", title: "Kvalita a kontrola", body: "Každá šarže prochází HPLC a LC-MS analýzou provedenou nezávislou laboratoří Janoshik. Certifikáty jsou dostupné přímo na produktových stránkách." },
  ],
  hu: [
    { n: "01", title: "Átláthatóság minden gyártási tételnél", body: "A PurePeptide kiemelt hangsúlyt fektet a világos terméktájékoztatásra, a laboratóriumi elemzésekre és a tételek nyomon követhetőségére. Így minden döntés adatokon alapulhat, nem túlzó állításokon." },
    { n: "02", title: "Tudományos fókuszú információk", body: "Leírásaink semleges és kutatási szemléletet követnek, amely publikált tudományos szakirodalmon és laboratóriumi kontextuson alapul. Célunk, hogy a tartalom pontos, érthető és hasznos legyen." },
    { n: "03", title: "Minőség és ellenőrzés", body: "Minden gyártási tétel HPLC és LC-MS elemzésen esik át a független Janoshik laboratóriumban. A tanúsítványok közvetlenül elérhetők a termékoldalakon." },
  ],
  pl: [
    { n: "01", title: "Przejrzystość w każdej partii", body: "PurePeptide kładzie nacisk na jasne informacje o produkcie, analizy laboratoryjne i śledzenie partii. Dzięki temu każda decyzja może być oparta na danych, a nie na wygórowanych twierdzeniach." },
    { n: "02", title: "Informacje o charakterze naukowym", body: "Nasze opisy stosują neutralne, badawcze podejście, oparte na opublikowanej literaturze naukowej i kontekście laboratoryjnym. Celem jest, aby treść była precyzyjna, zrozumiała i użyteczna." },
    { n: "03", title: "Jakość i kontrola", body: "Każda partia przechodzi analizę HPLC i LC-MS wykonywaną przez niezależne laboratorium Janoshik. Certyfikaty są dostępne bezpośrednio na stronach produktów." },
  ],
  sk: [
    { n: "01", title: "Transparentnosť v každej šarži", body: "PurePeptide kladie dôraz na jasné informácie o produktoch, laboratórne analýzy a sledovateľnosť šarží. Tak môže byť každé rozhodnutie založené na dátach, nie na prehnaných tvrdeniach." },
    { n: "02", title: "Informácie so zameraním na výskum", body: "Naše popisy sa riadia neutrálnym a výskumným prístupom, založeným na publikovanej vedeckej literatúre a laboratórnom kontexte. Cieľom je, aby bol obsah presný, zrozumiteľný a užitočný." },
    { n: "03", title: "Kvalita a kontrola", body: "Každá šarža prechádza HPLC a LC-MS analýzou vykonanou nezávislým laboratóriom Janoshik. Certifikáty sú dostupné priamo na stránkach produktov." },
  ],
  si: [
    { n: "01", title: "Preglednost v vsaki seriji", body: "PurePeptide poudarja jasne informacije o izdelkih, laboratorijske analize in sledljivost serij. Tako lahko vsaka odločitev temelji na podatkih, ne na pretiranih trditvah." },
    { n: "02", title: "Informacije z znanstvenim poudarkom", body: "Naši opisi sledijo nevtralnemu in raziskovalno usmerjenemu pristopu, ki temelji na objavljeni znanstveni literaturi in laboratorijskem kontekstu. Cilj je, da je vsebina natančna, razumljiva in koristna." },
    { n: "03", title: "Kakovost in nadzor", body: "Vsaka serija je podvržena HPLC in LC-MS analizi neodvisnega laboratorija Janoshik. Certifikati so na voljo neposredno na straneh izdelkov." },
  ],
  gr: [
    { n: "01", title: "Διαφάνεια σε κάθε παρτίδα", body: "Η PurePeptide δίνει έμφαση σε σαφείς πληροφορίες προϊόντος, εργαστηριακές αναλύσεις και ιχνηλασιμότητα παρτίδων. Έτσι, κάθε απόφαση μπορεί να βασίζεται σε δεδομένα και όχι σε υπερβολικούς ισχυρισμούς." },
    { n: "02", title: "Πληροφορίες με επιστημονική εστίαση", body: "Οι περιγραφές μας ακολουθούν μια ουδέτερη και ερευνητική προσέγγιση, βασισμένη σε δημοσιευμένη επιστημονική βιβλιογραφία και εργαστηριακό πλαίσιο. Στόχος είναι το περιεχόμενο να είναι ακριβές, κατανοητό και χρήσιμο." },
    { n: "03", title: "Ποιότητα και έλεγχος", body: "Κάθε παρτίδα υποβάλλεται σε ανάλυση HPLC και LC-MS από το ανεξάρτητο εργαστήριο Janoshik. Τα πιστοποιητικά είναι διαθέσιμα απευθείας στις σελίδες προϊόντων." },
  ],
  ro: [
    { n: "01", title: "Transparență în fiecare lot", body: "PurePeptide pune accent pe informații clare despre produse, analize de laborator și trasabilitatea loturilor. Astfel, fiecare decizie poate fi bazată pe date, nu pe afirmații exagerate." },
    { n: "02", title: "Informații cu focus științific", body: "Descrierile noastre urmează o abordare neutră și orientată spre cercetare, bazată pe literatura științifică publicată și pe context de laborator. Scopul este ca conținutul să fie precis, ușor de înțeles și util." },
    { n: "03", title: "Calitate și control", body: "Fiecare lot trece prin analize HPLC și LC-MS efectuate de laboratorul independent Janoshik. Certificatele sunt disponibile direct pe paginile produselor." },
  ],
};

export const FAQ_GEN = {
  en: [
    { q: "What sets PurePeptide's peptides apart?", a: "Transparency and quality control. Every product is lyophilized for a longer shelf life and has undergone HPLC and LC-MS analysis with a purity above 99%. Testing is carried out by the Czech laboratory Janoshik." },
    { q: "How can I check the certificates of analysis?", a: "Every product has a certificate of analysis (CoA) performed by Janoshik Labs. The documents are available on the product pages and contain a batch number." },
    { q: "How long are unreconstituted peptides stable?", a: "In lyophilized form at 2–8°C, peptides remain stable for up to 24 months. At room temperature – about 3–4 months." },
    { q: "How long does delivery take?", a: "Shipments are sent with tracking via a local courier and typically arrive within 1–3 business days." },
  ],
  fr: [
    { q: "Qu'est-ce qui distingue les peptides de PurePeptide ?", a: "Transparence et contrôle qualité. Chaque produit est lyophilisé pour une durée de conservation plus longue et a fait l'objet d'une analyse HPLC et LC-MS avec une pureté supérieure à 99%. Les tests sont effectués par le laboratoire tchèque Janoshik." },
    { q: "Comment puis-je consulter les certificats d'analyse ?", a: "Chaque produit dispose d'un certificat d'analyse (CoA), réalisé par Janoshik Labs. Les documents sont disponibles sur les pages produits et contiennent le numéro de lot." },
    { q: "Combien de temps les peptides non dissous restent-ils stables ?", a: "Sous forme lyophilisée à 2–8°C, les peptides conservent leur stabilité jusqu'à 24 mois. À température ambiante – environ 3 à 4 mois." },
    { q: "Combien de temps prend la livraison ?", a: "Les colis sont expédiés avec suivi via un transporteur local et arrivent généralement dans un délai de 1 à 3 jours ouvrables." },
  ],
  de: [
    { q: "Was zeichnet die Peptide von PurePeptide aus?", a: "Transparenz und Qualitätskontrolle. Jedes Produkt ist lyophilisiert für eine längere Haltbarkeit und hat eine HPLC- und LC-MS-Analyse mit einer Reinheit von über 99% durchlaufen. Die Tests werden vom tschechischen Labor Janoshik durchgeführt." },
    { q: "Wie kann ich die Analysezertifikate überprüfen?", a: "Jedes Produkt verfügt über ein Analysezertifikat (CoA), das von Janoshik Labs durchgeführt wurde. Die Dokumente sind auf den Produktseiten verfügbar und enthalten die Chargennummer." },
    { q: "Wie lange sind unaufgelöste Peptide stabil?", a: "In lyophilisierter Form bei 2–8°C bleiben Peptide bis zu 24 Monate stabil. Bei Raumtemperatur – etwa 3–4 Monate." },
    { q: "Wie lange dauert die Lieferung?", a: "Sendungen werden mit Sendungsverfolgung durch einen lokalen Kurierdienst versendet und kommen in der Regel innerhalb von 1–3 Werktagen an." },
  ],
  cz: [
    { q: "Co odlišuje peptidy PurePeptide?", a: "Transparentnost a kontrola kvality. Každý produkt je lyofilizovaný pro delší dobu uchovávání a prošel HPLC a LC-MS analýzou s čistotou nad 99 %. Testy provádí česká laboratoř Janoshik." },
    { q: "Jak si mohu ověřit certifikáty analýzy?", a: "Každý produkt disponuje certifikátem analýzy (CoA) provedeným laboratoří Janoshik Labs. Dokumenty jsou dostupné na produktových stránkách a obsahují číslo šarže." },
    { q: "Jak dlouho jsou nerozpuštěné peptidy stabilní?", a: "V lyofilizované formě při teplotě 2–8 °C si peptidy zachovávají stabilitu až 24 měsíců. Při pokojové teplotě přibližně 3–4 měsíce." },
    { q: "Jak dlouho trvá doručení?", a: "Zásilky jsou odesílány se sledováním prostřednictvím místního přepravce a obvykle dorazí do 1–3 pracovních dnů." },
  ],
  hu: [
    { q: "Mi különbözteti meg a PurePeptide peptidjeit?", a: "Az átláthatóság és a minőségellenőrzés. Minden termék liofilizált a hosszabb eltarthatóság érdekében, és HPLC valamint LC-MS elemzésen esett át, 99% feletti tisztasággal. A teszteket a cseh Janoshik laboratórium végzi." },
    { q: "Hogyan ellenőrizhetem az elemzési tanúsítványokat?", a: "Minden termékhez rendelkezésre áll egy elemzési tanúsítvány (CoA), amelyet a Janoshik Labs készített. A dokumentumok elérhetők a termékoldalakon, és tartalmazzák a tétel számát." },
    { q: "Meddig stabilak a fel nem oldott peptidek?", a: "Liofilizált formában, 2–8°C-on a peptidek akár 24 hónapig is stabilak maradnak. Szobahőmérsékleten körülbelül 3–4 hónapig." },
    { q: "Mennyi ideig tart a szállítás?", a: "A csomagokat nyomon követéssel, helyi futárszolgálat útján küldjük, és általában 1–3 munkanapon belül megérkeznek." },
  ],
  pl: [
    { q: "Co wyróżnia peptydy PurePeptide?", a: "Przejrzystość i kontrola jakości. Każdy produkt jest liofilizowany dla dłuższego okresu przechowywania i przeszedł analizę HPLC i LC-MS z czystością powyżej 99%. Testy są wykonywane przez czeskie laboratorium Janoshik." },
    { q: "Jak mogę sprawdzić certyfikaty analizy?", a: "Każdy produkt posiada certyfikat analizy (CoA) wykonany przez Janoshik Labs. Dokumenty są dostępne na stronach produktów i zawierają numer partii." },
    { q: "Jak długo są stabilne nierozpuszczone peptydy?", a: "W formie liofilizowanej przy 2–8°C peptydy zachowują stabilność do 24 miesięcy. W temperaturze pokojowej – około 3–4 miesiące." },
    { q: "Ile czasu zajmuje dostawa?", a: "Przesyłki są wysyłane z możliwością śledzenia przez lokalnego kuriera i zazwyczaj docierają w ciągu 1–3 dni roboczych." },
  ],
  sk: [
    { q: "Čo odlišuje peptidy PurePeptide?", a: "Transparentnosť a kontrola kvality. Každý produkt je lyofilizovaný pre dlhšiu dobu uchovávania a prešiel HPLC a LC-MS analýzou s čistotou nad 99%. Testy vykonáva české laboratórium Janoshik." },
    { q: "Ako môžem overiť certifikáty analýzy?", a: "Každý produkt má k dispozícii certifikát o analýze (CoA), vykonaný spoločnosťou Janoshik Labs. Dokumenty sú dostupné na stránkach produktov a obsahujú číslo šarže." },
    { q: "Ako dlho sú nerozpustené peptidy stabilné?", a: "V lyofilizovanej forme pri 2–8°C si peptidy zachovávajú stabilitu až 24 mesiacov. Pri izbovej teplote – približne 3–4 mesiace." },
    { q: "Ako dlho trvá doručenie?", a: "Zásielky sa odosielajú so sledovaním prostredníctvom miestneho kuriéra a zvyčajne prichádzajú do 1–3 pracovných dní." },
  ],
  si: [
    { q: "Kaj odlikuje peptide PurePeptide?", a: "Preglednost in nadzor kakovosti. Vsak izdelek je liofiliziran za daljši rok trajanja in je bil podvržen HPLC in LC-MS analizi s čistostjo nad 99%. Teste izvaja češki laboratorij Janoshik." },
    { q: "Kako lahko preverim certifikate analize?", a: "Vsak izdelek ima certifikat o analizi (CoA), ki ga izvede Janoshik Labs. Dokumenti so na voljo na straneh izdelkov in vsebujejo številko serije." },
    { q: "Koliko časa so stabilni neraztopljeni peptidi?", a: "V liofilizirani obliki pri 2–8°C peptidi ohranjajo stabilnost do 24 mesecev. Pri sobni temperaturi približno 3–4 mesece." },
    { q: "Koliko časa traja dostava?", a: "Pošiljke se pošiljajo s sledenjem prek lokalnega kurirja in običajno prispejo v roku 1–3 delovnih dni." },
  ],
  gr: [
    { q: "Τι διαφοροποιεί τα πεπτίδια της PurePeptide;", a: "Διαφάνεια και έλεγχος ποιότητας. Κάθε προϊόν είναι λυοφιλιωμένο για μεγαλύτερη διάρκεια αποθήκευσης και έχει υποβληθεί σε ανάλυση HPLC και LC-MS με καθαρότητα άνω του 99%. Οι δοκιμές πραγματοποιούνται από το τσεχικό εργαστήριο Janoshik." },
    { q: "Πώς μπορώ να ελέγξω τα πιστοποιητικά ανάλυσης;", a: "Κάθε προϊόν διαθέτει πιστοποιητικό ανάλυσης (CoA), που εκτελείται από την Janoshik Labs. Τα έγγραφα είναι διαθέσιμα στις σελίδες προϊόντων και περιέχουν αριθμό παρτίδας." },
    { q: "Πόσο καιρό είναι σταθερά τα μη διαλυμένα πεπτίδια;", a: "Σε λυοφιλιωμένη μορφή στους 2–8°C τα πεπτίδια διατηρούν τη σταθερότητά τους έως 24 μήνες. Σε θερμοκρασία δωματίου – περίπου 3–4 μήνες." },
    { q: "Πόσο χρόνο διαρκεί η παράδοση;", a: "Οι αποστολές γίνονται με ιχνηλάτηση μέσω τοπικής μεταφορικής εταιρείας και συνήθως φτάνουν εντός 1–3 εργάσιμων ημερών." },
  ],
  ro: [
    { q: "Ce diferențiază peptidele PurePeptide?", a: "Transparență și control al calității. Fiecare produs este liofilizat pentru o durată de conservare mai lungă și a trecut prin analize HPLC și LC-MS cu o puritate de peste 99%. Testele sunt efectuate de laboratorul ceh Janoshik." },
    { q: "Cum pot verifica certificatele de analiză?", a: "Fiecare produs dispune de un certificat de analiză (CoA), realizat de Janoshik Labs. Documentele sunt disponibile pe paginile produselor și conțin numărul lotului." },
    { q: "Cât timp sunt stabile peptidele nedizolvate?", a: "În formă liofilizată, la 2–8°C, peptidele își păstrează stabilitatea până la 24 de luni. La temperatura camerei – aproximativ 3–4 luni." },
    { q: "Cât durează livrarea?", a: "Coletele sunt expediate cu urmărire prin curier local și, de obicei, ajung în termen de 1–3 zile lucrătoare." },
  ],
};
